# inventory/hosts.yml

all:
  hosts:
    192.168.200.24:
      ansible_user: vid
      ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
      ansible_connection: ssh
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  children:
    video_digitization_stations:
      hosts:
        192.168.200.24
